### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by FranklinOP-IND** [xEnething/Valorant-Cheat#1]
![image](https://user-images.githubusercontent.com/64591314/132448007-112727ec-3ceb-4499-aa1f-539d5d485456.png)
 iam ignore error them i will show this
 
![image](https://user-images.githubusercontent.com/64591314/132448086-5cb80998-a8e7-47d1-861f-8229b5daea90.png)

**Comment by xEnething** [comment]
user issue. Maybe try on another pc / ask a friend
